// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/currency.proto

package g2u

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdminRequest struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminRequest) Reset()         { *m = AdminRequest{} }
func (m *AdminRequest) String() string { return proto.CompactTextString(m) }
func (*AdminRequest) ProtoMessage()    {}
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_currency_5f4c1185368f37fa, []int{0}
}
func (m *AdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRequest.Unmarshal(m, b)
}
func (m *AdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRequest.Marshal(b, m, deterministic)
}
func (dst *AdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRequest.Merge(dst, src)
}
func (m *AdminRequest) XXX_Size() int {
	return xxx_messageInfo_AdminRequest.Size(m)
}
func (m *AdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRequest proto.InternalMessageInfo

func (m *AdminRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type AdminResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message              int32    `protobuf:"varint,2,opt,name=message" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminResponse) Reset()         { *m = AdminResponse{} }
func (m *AdminResponse) String() string { return proto.CompactTextString(m) }
func (*AdminResponse) ProtoMessage()    {}
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_currency_5f4c1185368f37fa, []int{1}
}
func (m *AdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminResponse.Unmarshal(m, b)
}
func (m *AdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminResponse.Marshal(b, m, deterministic)
}
func (dst *AdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminResponse.Merge(dst, src)
}
func (m *AdminResponse) XXX_Size() int {
	return xxx_messageInfo_AdminResponse.Size(m)
}
func (m *AdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminResponse proto.InternalMessageInfo

func (m *AdminResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AdminResponse) GetMessage() int32 {
	if m != nil {
		return m.Message
	}
	return 0
}

func (m *AdminResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*AdminRequest)(nil), "g2u.AdminRequest")
	proto.RegisterType((*AdminResponse)(nil), "g2u.AdminResponse")
}

func init() { proto.RegisterFile("rpc/currency.proto", fileDescriptor_currency_5f4c1185368f37fa) }

var fileDescriptor_currency_5f4c1185368f37fa = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4d, 0xce, 0x82, 0x40,
	0x0c, 0x86, 0x3f, 0x3e, 0xfc, 0xad, 0x9a, 0x68, 0x57, 0x13, 0x57, 0x84, 0x95, 0x2b, 0x4c, 0xe0,
	0x04, 0xca, 0x05, 0x74, 0x6e, 0x80, 0x33, 0x0d, 0x71, 0x31, 0x0c, 0xce, 0xcf, 0xc2, 0xdb, 0x1b,
	0x2a, 0x26, 0xec, 0xde, 0xbe, 0x79, 0xd2, 0x3e, 0x05, 0x74, 0xbd, 0x3a, 0xab, 0xe8, 0x1c, 0x75,
	0xea, 0x5d, 0xf4, 0xce, 0x06, 0x8b, 0x69, 0x5b, 0xc6, 0x3c, 0x83, 0xed, 0x45, 0x9b, 0x67, 0x27,
	0xe9, 0x15, 0xc9, 0x07, 0xdc, 0x43, 0xaa, 0x8c, 0x16, 0x49, 0x96, 0x9c, 0xd6, 0x72, 0x88, 0xf9,
	0x1d, 0x76, 0x23, 0xe1, 0x7b, 0xdb, 0x79, 0x42, 0x84, 0x99, 0xb2, 0x9a, 0x98, 0x99, 0x4b, 0xce,
	0x28, 0x60, 0x69, 0xc8, 0xfb, 0xa6, 0x25, 0xf1, 0xcf, 0xf5, 0x6f, 0x1c, 0x68, 0xdd, 0x84, 0x46,
	0xa4, 0xbc, 0x91, 0x73, 0x79, 0x85, 0x4d, 0x3d, 0xba, 0xc8, 0x5b, 0x8d, 0x15, 0xac, 0xf8, 0x42,
	0x6d, 0x34, 0x1e, 0x8a, 0xb6, 0x8c, 0xc5, 0x54, 0xe9, 0x88, 0xd3, 0xea, 0xeb, 0x90, 0xff, 0x3d,
	0x16, 0xfc, 0x44, 0xf5, 0x09, 0x00, 0x00, 0xff, 0xff, 0xae, 0x52, 0x8f, 0x69, 0xda, 0x00, 0x00,
	0x00,
}
