// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/user.proto

package g2u

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommonErrResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonErrResponse) Reset()         { *m = CommonErrResponse{} }
func (m *CommonErrResponse) String() string { return proto.CompactTextString(m) }
func (*CommonErrResponse) ProtoMessage()    {}
func (*CommonErrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{0}
}
func (m *CommonErrResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonErrResponse.Unmarshal(m, b)
}
func (m *CommonErrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonErrResponse.Marshal(b, m, deterministic)
}
func (dst *CommonErrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonErrResponse.Merge(dst, src)
}
func (m *CommonErrResponse) XXX_Size() int {
	return xxx_messageInfo_CommonErrResponse.Size(m)
}
func (m *CommonErrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonErrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonErrResponse proto.InternalMessageInfo

func (m *CommonErrResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *CommonErrResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{1}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{2}
}
func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (dst *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(dst, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type RegisterRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
	InviteCode           string   `protobuf:"bytes,4,opt,name=invite_code,json=inviteCode" json:"invite_code,omitempty"`
	Country              int32    `protobuf:"varint,5,opt,name=country" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{3}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *RegisterRequest) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *RegisterRequest) GetCountry() int32 {
	if m != nil {
		return m.Country
	}
	return 0
}

type RegisterResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{4}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

type LoginRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{5}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type LoginResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{6}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

type ForgetRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetRequest) Reset()         { *m = ForgetRequest{} }
func (m *ForgetRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetRequest) ProtoMessage()    {}
func (*ForgetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{7}
}
func (m *ForgetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetRequest.Unmarshal(m, b)
}
func (m *ForgetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetRequest.Marshal(b, m, deterministic)
}
func (dst *ForgetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetRequest.Merge(dst, src)
}
func (m *ForgetRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetRequest.Size(m)
}
func (m *ForgetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetRequest proto.InternalMessageInfo

func (m *ForgetRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ForgetResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetResponse) Reset()         { *m = ForgetResponse{} }
func (m *ForgetResponse) String() string { return proto.CompactTextString(m) }
func (*ForgetResponse) ProtoMessage()    {}
func (*ForgetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{8}
}
func (m *ForgetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetResponse.Unmarshal(m, b)
}
func (m *ForgetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetResponse.Marshal(b, m, deterministic)
}
func (dst *ForgetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetResponse.Merge(dst, src)
}
func (m *ForgetResponse) XXX_Size() int {
	return xxx_messageInfo_ForgetResponse.Size(m)
}
func (m *ForgetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetResponse proto.InternalMessageInfo

func (m *ForgetResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *ForgetResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ForgetResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ForgetResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SecurityRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	PhoneAuthCode        string   `protobuf:"bytes,2,opt,name=phone_auth_code,json=phoneAuthCode" json:"phone_auth_code,omitempty"`
	EmailAuthCode        string   `protobuf:"bytes,3,opt,name=email_auth_code,json=emailAuthCode" json:"email_auth_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityRequest) Reset()         { *m = SecurityRequest{} }
func (m *SecurityRequest) String() string { return proto.CompactTextString(m) }
func (*SecurityRequest) ProtoMessage()    {}
func (*SecurityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{9}
}
func (m *SecurityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityRequest.Unmarshal(m, b)
}
func (m *SecurityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityRequest.Marshal(b, m, deterministic)
}
func (dst *SecurityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityRequest.Merge(dst, src)
}
func (m *SecurityRequest) XXX_Size() int {
	return xxx_messageInfo_SecurityRequest.Size(m)
}
func (m *SecurityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityRequest proto.InternalMessageInfo

func (m *SecurityRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SecurityRequest) GetPhoneAuthCode() string {
	if m != nil {
		return m.PhoneAuthCode
	}
	return ""
}

func (m *SecurityRequest) GetEmailAuthCode() string {
	if m != nil {
		return m.EmailAuthCode
	}
	return ""
}

type SecurityResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	SecurityKey          []byte   `protobuf:"bytes,3,opt,name=security_key,json=securityKey,proto3" json:"security_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityResponse) Reset()         { *m = SecurityResponse{} }
func (m *SecurityResponse) String() string { return proto.CompactTextString(m) }
func (*SecurityResponse) ProtoMessage()    {}
func (*SecurityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{10}
}
func (m *SecurityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityResponse.Unmarshal(m, b)
}
func (m *SecurityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityResponse.Marshal(b, m, deterministic)
}
func (dst *SecurityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityResponse.Merge(dst, src)
}
func (m *SecurityResponse) XXX_Size() int {
	return xxx_messageInfo_SecurityResponse.Size(m)
}
func (m *SecurityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityResponse proto.InternalMessageInfo

func (m *SecurityResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *SecurityResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SecurityResponse) GetSecurityKey() []byte {
	if m != nil {
		return m.SecurityKey
	}
	return nil
}

type SmsRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsRequest) Reset()         { *m = SmsRequest{} }
func (m *SmsRequest) String() string { return proto.CompactTextString(m) }
func (*SmsRequest) ProtoMessage()    {}
func (*SmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{11}
}
func (m *SmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsRequest.Unmarshal(m, b)
}
func (m *SmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsRequest.Marshal(b, m, deterministic)
}
func (dst *SmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsRequest.Merge(dst, src)
}
func (m *SmsRequest) XXX_Size() int {
	return xxx_messageInfo_SmsRequest.Size(m)
}
func (m *SmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsRequest proto.InternalMessageInfo

func (m *SmsRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type EmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{12}
}
func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (dst *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(dst, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ChangePwdRequest struct {
	SecurityKey          []byte   `protobuf:"bytes,1,opt,name=security_key,json=securityKey,proto3" json:"security_key,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePwdRequest) Reset()         { *m = ChangePwdRequest{} }
func (m *ChangePwdRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePwdRequest) ProtoMessage()    {}
func (*ChangePwdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1e733fdac6dd0517, []int{13}
}
func (m *ChangePwdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePwdRequest.Unmarshal(m, b)
}
func (m *ChangePwdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePwdRequest.Marshal(b, m, deterministic)
}
func (dst *ChangePwdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePwdRequest.Merge(dst, src)
}
func (m *ChangePwdRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePwdRequest.Size(m)
}
func (m *ChangePwdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePwdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePwdRequest proto.InternalMessageInfo

func (m *ChangePwdRequest) GetSecurityKey() []byte {
	if m != nil {
		return m.SecurityKey
	}
	return nil
}

func (m *ChangePwdRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonErrResponse)(nil), "g2u.CommonErrResponse")
	proto.RegisterType((*HelloRequest)(nil), "g2u.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "g2u.HelloResponse")
	proto.RegisterType((*RegisterRequest)(nil), "g2u.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "g2u.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "g2u.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "g2u.LoginResponse")
	proto.RegisterType((*ForgetRequest)(nil), "g2u.ForgetRequest")
	proto.RegisterType((*ForgetResponse)(nil), "g2u.ForgetResponse")
	proto.RegisterType((*SecurityRequest)(nil), "g2u.SecurityRequest")
	proto.RegisterType((*SecurityResponse)(nil), "g2u.SecurityResponse")
	proto.RegisterType((*SmsRequest)(nil), "g2u.SmsRequest")
	proto.RegisterType((*EmailRequest)(nil), "g2u.EmailRequest")
	proto.RegisterType((*ChangePwdRequest)(nil), "g2u.ChangePwdRequest")
}

func init() { proto.RegisterFile("rpc/user.proto", fileDescriptor_user_1e733fdac6dd0517) }

var fileDescriptor_user_1e733fdac6dd0517 = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5f, 0x6b, 0xdb, 0x3e,
	0x14, 0x4d, 0x9a, 0xfa, 0xd7, 0xe6, 0xd6, 0x69, 0x52, 0xfd, 0xb2, 0x11, 0xf2, 0xb2, 0x56, 0x74,
	0xa5, 0x30, 0xc8, 0x4a, 0x36, 0xca, 0x06, 0x1b, 0x63, 0x84, 0x6e, 0x83, 0xee, 0xa1, 0x38, 0xec,
	0x39, 0x78, 0xf1, 0xc5, 0x31, 0x8b, 0xa5, 0x4c, 0x92, 0x17, 0xfc, 0x35, 0xf7, 0x89, 0x86, 0xf5,
	0xc7, 0x71, 0x3c, 0x12, 0xe8, 0xde, 0xa4, 0xeb, 0x7b, 0xee, 0x39, 0x3a, 0x3a, 0x32, 0x9c, 0x8a,
	0xd5, 0xfc, 0x65, 0x26, 0x51, 0x8c, 0x56, 0x82, 0x2b, 0x4e, 0x5a, 0xf1, 0x38, 0xa3, 0x1f, 0xe0,
	0x6c, 0xc2, 0xd3, 0x94, 0xb3, 0x3b, 0x21, 0x02, 0x94, 0x2b, 0xce, 0x24, 0x92, 0x1e, 0xb4, 0x50,
	0x88, 0x41, 0xf3, 0xbc, 0x79, 0xed, 0x05, 0xc5, 0x92, 0x0c, 0xe0, 0x28, 0x45, 0x29, 0xc3, 0x18,
	0x07, 0x07, 0xe7, 0xcd, 0xeb, 0x76, 0xe0, 0xb6, 0x94, 0x82, 0xff, 0x05, 0x97, 0x4b, 0x1e, 0xe0,
	0xcf, 0x0c, 0xa5, 0x22, 0x04, 0x0e, 0x59, 0x98, 0xa2, 0x06, 0xb7, 0x03, 0xbd, 0xa6, 0x2f, 0xa0,
	0x63, 0x7b, 0x2c, 0xc1, 0x10, 0x8e, 0x63, 0x81, 0xa8, 0x12, 0x16, 0xdb, 0x79, 0xe5, 0x9e, 0x2a,
	0xe8, 0x06, 0x18, 0x27, 0x52, 0xa1, 0x70, 0x33, 0xfb, 0xe0, 0xad, 0x16, 0x9c, 0xb9, 0xa1, 0x66,
	0x53, 0xa8, 0x5c, 0xad, 0x23, 0x8b, 0x2f, 0x96, 0xe4, 0x19, 0x9c, 0x24, 0xec, 0x57, 0xa2, 0x70,
	0x36, 0xe7, 0x11, 0x0e, 0x0e, 0xf5, 0x17, 0x30, 0xa5, 0x09, 0x8f, 0xb0, 0x38, 0xc6, 0x9c, 0x67,
	0x4c, 0x89, 0x7c, 0xe0, 0xe9, 0xc3, 0xb9, 0x2d, 0xbd, 0x84, 0xde, 0x86, 0x75, 0x97, 0x0d, 0xf4,
	0x16, 0xfc, 0xaf, 0x3c, 0x4e, 0xd8, 0x23, 0x85, 0xd1, 0x0b, 0xe8, 0x58, 0xdc, 0xce, 0xd1, 0xcf,
	0xa1, 0xf3, 0x89, 0x8b, 0x18, 0xd5, 0xde, 0xd9, 0x74, 0x01, 0xa7, 0xae, 0xed, 0xf1, 0x97, 0xb5,
	0x99, 0xd9, 0xaa, 0xea, 0xed, 0x83, 0x87, 0x69, 0x98, 0x2c, 0xad, 0x61, 0x66, 0x43, 0xd7, 0xd0,
	0x9d, 0xe2, 0x3c, 0x13, 0x89, 0xca, 0xf7, 0x1f, 0xf7, 0x0a, 0xba, 0x7a, 0x31, 0x0b, 0x33, 0xb5,
	0x30, 0xce, 0x1b, 0xda, 0x8e, 0x2e, 0x7f, 0xcc, 0xd4, 0x42, 0x9b, 0x7f, 0x05, 0x5d, 0x3d, 0xb9,
	0xd2, 0x67, 0x64, 0x74, 0x74, 0xd9, 0xf5, 0xd1, 0x10, 0x7a, 0x1b, 0xe2, 0x7f, 0x38, 0xe4, 0x05,
	0xf8, 0xd2, 0xe2, 0x67, 0x3f, 0x30, 0xd7, 0x24, 0x7e, 0x70, 0xe2, 0x6a, 0xf7, 0x98, 0x53, 0x0a,
	0x30, 0x4d, 0xe5, 0x7e, 0xa7, 0x2f, 0xc1, 0xbf, 0x2b, 0x74, 0x55, 0xba, 0x8c, 0x4b, 0xcd, 0xaa,
	0x4b, 0xf7, 0xd0, 0x9b, 0x2c, 0x42, 0x16, 0xe3, 0xc3, 0x3a, 0x72, 0x9d, 0x75, 0x01, 0xcd, 0xbf,
	0x04, 0x6c, 0x28, 0x0f, 0x2a, 0x94, 0xe3, 0xdf, 0x2d, 0xf0, 0x3f, 0x87, 0x0a, 0xd7, 0x61, 0x3e,
	0xfe, 0x26, 0x51, 0x90, 0x1b, 0xf0, 0xf4, 0xc3, 0x21, 0x67, 0xa3, 0x78, 0x9c, 0x8d, 0xaa, 0x0f,
	0x6d, 0x48, 0xaa, 0x25, 0x63, 0x13, 0x6d, 0x90, 0xb7, 0x70, 0xec, 0x72, 0x4c, 0xfa, 0xba, 0xa3,
	0xf6, 0x98, 0x86, 0x4f, 0x6a, 0xd5, 0x12, 0x7a, 0x03, 0x9e, 0x0e, 0xa9, 0x25, 0xab, 0x06, 0xdd,
	0x92, 0x6d, 0x65, 0x98, 0x36, 0xc8, 0x2d, 0xb4, 0x4d, 0x18, 0x1f, 0xd6, 0x11, 0x31, 0x2d, 0x5b,
	0x19, 0x1e, 0xfe, 0xbf, 0x55, 0x2b, 0x71, 0xef, 0xc1, 0x2f, 0x6e, 0xdb, 0xdd, 0xb2, 0x15, 0x5a,
	0x4b, 0x9b, 0x15, 0x5a, 0x8f, 0x02, 0x6d, 0x90, 0x77, 0xd0, 0x2e, 0x3d, 0x27, 0xa6, 0xab, 0x7e,
	0x07, 0xc3, 0xa7, 0xa6, 0x5c, 0xff, 0xb5, 0xd1, 0x06, 0x79, 0x0d, 0x47, 0x53, 0x64, 0xd1, 0x34,
	0x95, 0xa4, 0x6b, 0x18, 0xca, 0x24, 0xec, 0x41, 0xbd, 0x81, 0x76, 0x81, 0xd2, 0x89, 0xb0, 0x06,
	0x55, 0xd3, 0xb1, 0x1b, 0xf9, 0xfd, 0x3f, 0xfd, 0xb7, 0x7d, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x04, 0x60, 0x23, 0xd1, 0x7f, 0x05, 0x00, 0x00,
}
