// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/user.proto

package g2u

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommonErrResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonErrResponse) Reset()         { *m = CommonErrResponse{} }
func (m *CommonErrResponse) String() string { return proto.CompactTextString(m) }
func (*CommonErrResponse) ProtoMessage()    {}
func (*CommonErrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{0}
}
func (m *CommonErrResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonErrResponse.Unmarshal(m, b)
}
func (m *CommonErrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonErrResponse.Marshal(b, m, deterministic)
}
func (dst *CommonErrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonErrResponse.Merge(dst, src)
}
func (m *CommonErrResponse) XXX_Size() int {
	return xxx_messageInfo_CommonErrResponse.Size(m)
}
func (m *CommonErrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonErrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonErrResponse proto.InternalMessageInfo

func (m *CommonErrResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *CommonErrResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{1}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{2}
}
func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (dst *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(dst, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type RegisterPhoneRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
	InviteCode           string   `protobuf:"bytes,4,opt,name=invite_code,json=inviteCode" json:"invite_code,omitempty"`
	Country              int32    `protobuf:"varint,5,opt,name=country" json:"country,omitempty"`
	Code                 string   `protobuf:"bytes,6,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterPhoneRequest) Reset()         { *m = RegisterPhoneRequest{} }
func (m *RegisterPhoneRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterPhoneRequest) ProtoMessage()    {}
func (*RegisterPhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{3}
}
func (m *RegisterPhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterPhoneRequest.Unmarshal(m, b)
}
func (m *RegisterPhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterPhoneRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterPhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterPhoneRequest.Merge(dst, src)
}
func (m *RegisterPhoneRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterPhoneRequest.Size(m)
}
func (m *RegisterPhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterPhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterPhoneRequest proto.InternalMessageInfo

func (m *RegisterPhoneRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterPhoneRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *RegisterPhoneRequest) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *RegisterPhoneRequest) GetCountry() int32 {
	if m != nil {
		return m.Country
	}
	return 0
}

func (m *RegisterPhoneRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RegisterEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
	InviteCode           string   `protobuf:"bytes,4,opt,name=invite_code,json=inviteCode" json:"invite_code,omitempty"`
	Country              int32    `protobuf:"varint,5,opt,name=country" json:"country,omitempty"`
	Code                 string   `protobuf:"bytes,6,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterEmailRequest) Reset()         { *m = RegisterEmailRequest{} }
func (m *RegisterEmailRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterEmailRequest) ProtoMessage()    {}
func (*RegisterEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{4}
}
func (m *RegisterEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterEmailRequest.Unmarshal(m, b)
}
func (m *RegisterEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterEmailRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterEmailRequest.Merge(dst, src)
}
func (m *RegisterEmailRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterEmailRequest.Size(m)
}
func (m *RegisterEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterEmailRequest proto.InternalMessageInfo

func (m *RegisterEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterEmailRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *RegisterEmailRequest) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *RegisterEmailRequest) GetCountry() int32 {
	if m != nil {
		return m.Country
	}
	return 0
}

func (m *RegisterEmailRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LoginRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{5}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type LoginResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{6}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ForgetRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetRequest) Reset()         { *m = ForgetRequest{} }
func (m *ForgetRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetRequest) ProtoMessage()    {}
func (*ForgetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{7}
}
func (m *ForgetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetRequest.Unmarshal(m, b)
}
func (m *ForgetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetRequest.Marshal(b, m, deterministic)
}
func (dst *ForgetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetRequest.Merge(dst, src)
}
func (m *ForgetRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetRequest.Size(m)
}
func (m *ForgetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetRequest proto.InternalMessageInfo

func (m *ForgetRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ForgetResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetResponse) Reset()         { *m = ForgetResponse{} }
func (m *ForgetResponse) String() string { return proto.CompactTextString(m) }
func (*ForgetResponse) ProtoMessage()    {}
func (*ForgetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{8}
}
func (m *ForgetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetResponse.Unmarshal(m, b)
}
func (m *ForgetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetResponse.Marshal(b, m, deterministic)
}
func (dst *ForgetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetResponse.Merge(dst, src)
}
func (m *ForgetResponse) XXX_Size() int {
	return xxx_messageInfo_ForgetResponse.Size(m)
}
func (m *ForgetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetResponse proto.InternalMessageInfo

func (m *ForgetResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *ForgetResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ForgetResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ForgetResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SecurityRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	PhoneAuthCode        string   `protobuf:"bytes,2,opt,name=phone_auth_code,json=phoneAuthCode" json:"phone_auth_code,omitempty"`
	EmailAuthCode        string   `protobuf:"bytes,3,opt,name=email_auth_code,json=emailAuthCode" json:"email_auth_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityRequest) Reset()         { *m = SecurityRequest{} }
func (m *SecurityRequest) String() string { return proto.CompactTextString(m) }
func (*SecurityRequest) ProtoMessage()    {}
func (*SecurityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{9}
}
func (m *SecurityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityRequest.Unmarshal(m, b)
}
func (m *SecurityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityRequest.Marshal(b, m, deterministic)
}
func (dst *SecurityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityRequest.Merge(dst, src)
}
func (m *SecurityRequest) XXX_Size() int {
	return xxx_messageInfo_SecurityRequest.Size(m)
}
func (m *SecurityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityRequest proto.InternalMessageInfo

func (m *SecurityRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SecurityRequest) GetPhoneAuthCode() string {
	if m != nil {
		return m.PhoneAuthCode
	}
	return ""
}

func (m *SecurityRequest) GetEmailAuthCode() string {
	if m != nil {
		return m.EmailAuthCode
	}
	return ""
}

type SecurityResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	SecurityKey          []byte   `protobuf:"bytes,3,opt,name=security_key,json=securityKey,proto3" json:"security_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityResponse) Reset()         { *m = SecurityResponse{} }
func (m *SecurityResponse) String() string { return proto.CompactTextString(m) }
func (*SecurityResponse) ProtoMessage()    {}
func (*SecurityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{10}
}
func (m *SecurityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityResponse.Unmarshal(m, b)
}
func (m *SecurityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityResponse.Marshal(b, m, deterministic)
}
func (dst *SecurityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityResponse.Merge(dst, src)
}
func (m *SecurityResponse) XXX_Size() int {
	return xxx_messageInfo_SecurityResponse.Size(m)
}
func (m *SecurityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityResponse proto.InternalMessageInfo

func (m *SecurityResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *SecurityResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SecurityResponse) GetSecurityKey() []byte {
	if m != nil {
		return m.SecurityKey
	}
	return nil
}

type SmsRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsRequest) Reset()         { *m = SmsRequest{} }
func (m *SmsRequest) String() string { return proto.CompactTextString(m) }
func (*SmsRequest) ProtoMessage()    {}
func (*SmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{11}
}
func (m *SmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsRequest.Unmarshal(m, b)
}
func (m *SmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsRequest.Marshal(b, m, deterministic)
}
func (dst *SmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsRequest.Merge(dst, src)
}
func (m *SmsRequest) XXX_Size() int {
	return xxx_messageInfo_SmsRequest.Size(m)
}
func (m *SmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsRequest proto.InternalMessageInfo

func (m *SmsRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SmsRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type EmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{12}
}
func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (dst *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(dst, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ChangePwdRequest struct {
	SecurityKey          []byte   `protobuf:"bytes,1,opt,name=security_key,json=securityKey,proto3" json:"security_key,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePwdRequest) Reset()         { *m = ChangePwdRequest{} }
func (m *ChangePwdRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePwdRequest) ProtoMessage()    {}
func (*ChangePwdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{13}
}
func (m *ChangePwdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePwdRequest.Unmarshal(m, b)
}
func (m *ChangePwdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePwdRequest.Marshal(b, m, deterministic)
}
func (dst *ChangePwdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePwdRequest.Merge(dst, src)
}
func (m *ChangePwdRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePwdRequest.Size(m)
}
func (m *ChangePwdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePwdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePwdRequest proto.InternalMessageInfo

func (m *ChangePwdRequest) GetSecurityKey() []byte {
	if m != nil {
		return m.SecurityKey
	}
	return nil
}

func (m *ChangePwdRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type NoticeListRequest struct {
	NoticeType           int32    `protobuf:"varint,1,opt,name=NoticeType" json:"NoticeType,omitempty"`
	StartRow             int32    `protobuf:"varint,2,opt,name=StartRow" json:"StartRow,omitempty"`
	EndRow               int32    `protobuf:"varint,3,opt,name=EndRow" json:"EndRow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeListRequest) Reset()         { *m = NoticeListRequest{} }
func (m *NoticeListRequest) String() string { return proto.CompactTextString(m) }
func (*NoticeListRequest) ProtoMessage()    {}
func (*NoticeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{14}
}
func (m *NoticeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeListRequest.Unmarshal(m, b)
}
func (m *NoticeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeListRequest.Marshal(b, m, deterministic)
}
func (dst *NoticeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeListRequest.Merge(dst, src)
}
func (m *NoticeListRequest) XXX_Size() int {
	return xxx_messageInfo_NoticeListRequest.Size(m)
}
func (m *NoticeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeListRequest proto.InternalMessageInfo

func (m *NoticeListRequest) GetNoticeType() int32 {
	if m != nil {
		return m.NoticeType
	}
	return 0
}

func (m *NoticeListRequest) GetStartRow() int32 {
	if m != nil {
		return m.StartRow
	}
	return 0
}

func (m *NoticeListRequest) GetEndRow() int32 {
	if m != nil {
		return m.EndRow
	}
	return 0
}

type NoticeListResponse struct {
	Notice               []*NoticeListResponse_Notice `protobuf:"bytes,1,rep,name=notice" json:"notice,omitempty"`
	Err                  int32                        `protobuf:"varint,2,opt,name=err" json:"err,omitempty"`
	Message              string                       `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *NoticeListResponse) Reset()         { *m = NoticeListResponse{} }
func (m *NoticeListResponse) String() string { return proto.CompactTextString(m) }
func (*NoticeListResponse) ProtoMessage()    {}
func (*NoticeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{15}
}
func (m *NoticeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeListResponse.Unmarshal(m, b)
}
func (m *NoticeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeListResponse.Marshal(b, m, deterministic)
}
func (dst *NoticeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeListResponse.Merge(dst, src)
}
func (m *NoticeListResponse) XXX_Size() int {
	return xxx_messageInfo_NoticeListResponse.Size(m)
}
func (m *NoticeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeListResponse proto.InternalMessageInfo

func (m *NoticeListResponse) GetNotice() []*NoticeListResponse_Notice {
	if m != nil {
		return m.Notice
	}
	return nil
}

func (m *NoticeListResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *NoticeListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type NoticeListResponse_Notice struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
	CreateDateTime       string   `protobuf:"bytes,4,opt,name=createDateTime" json:"createDateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeListResponse_Notice) Reset()         { *m = NoticeListResponse_Notice{} }
func (m *NoticeListResponse_Notice) String() string { return proto.CompactTextString(m) }
func (*NoticeListResponse_Notice) ProtoMessage()    {}
func (*NoticeListResponse_Notice) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{15, 0}
}
func (m *NoticeListResponse_Notice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeListResponse_Notice.Unmarshal(m, b)
}
func (m *NoticeListResponse_Notice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeListResponse_Notice.Marshal(b, m, deterministic)
}
func (dst *NoticeListResponse_Notice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeListResponse_Notice.Merge(dst, src)
}
func (m *NoticeListResponse_Notice) XXX_Size() int {
	return xxx_messageInfo_NoticeListResponse_Notice.Size(m)
}
func (m *NoticeListResponse_Notice) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeListResponse_Notice.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeListResponse_Notice proto.InternalMessageInfo

func (m *NoticeListResponse_Notice) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NoticeListResponse_Notice) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NoticeListResponse_Notice) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NoticeListResponse_Notice) GetCreateDateTime() string {
	if m != nil {
		return m.CreateDateTime
	}
	return ""
}

type NoticeDetailRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeDetailRequest) Reset()         { *m = NoticeDetailRequest{} }
func (m *NoticeDetailRequest) String() string { return proto.CompactTextString(m) }
func (*NoticeDetailRequest) ProtoMessage()    {}
func (*NoticeDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{16}
}
func (m *NoticeDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeDetailRequest.Unmarshal(m, b)
}
func (m *NoticeDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeDetailRequest.Marshal(b, m, deterministic)
}
func (dst *NoticeDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeDetailRequest.Merge(dst, src)
}
func (m *NoticeDetailRequest) XXX_Size() int {
	return xxx_messageInfo_NoticeDetailRequest.Size(m)
}
func (m *NoticeDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeDetailRequest proto.InternalMessageInfo

func (m *NoticeDetailRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NoticeDetailResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	Covers               []byte   `protobuf:"bytes,7,opt,name=covers,proto3" json:"covers,omitempty"`
	ContentImages        []byte   `protobuf:"bytes,8,opt,name=content_images,json=contentImages,proto3" json:"content_images,omitempty"`
	Type                 int32    `protobuf:"varint,9,opt,name=type" json:"type,omitempty"`
	TypeName             string   `protobuf:"bytes,10,opt,name=type_name,json=typeName" json:"type_name,omitempty"`
	Author               string   `protobuf:"bytes,11,opt,name=author" json:"author,omitempty"`
	Weight               int32    `protobuf:"varint,12,opt,name=weight" json:"weight,omitempty"`
	Shares               int32    `protobuf:"varint,13,opt,name=shares" json:"shares,omitempty"`
	Hits                 int32    `protobuf:"varint,14,opt,name=hits" json:"hits,omitempty"`
	Comments             int32    `protobuf:"varint,15,opt,name=comments" json:"comments,omitempty"`
	DisplayMark          bool     `protobuf:"varint,16,opt,name=DisplayMark" json:"DisplayMark,omitempty"`
	CreateTime           string   `protobuf:"bytes,17,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,18,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	AdminId              int32    `protobuf:"varint,19,opt,name=adminId" json:"adminId,omitempty"`
	AdminNickname        string   `protobuf:"bytes,20,opt,name=admin_nickname,json=adminNickname" json:"admin_nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeDetailResponse) Reset()         { *m = NoticeDetailResponse{} }
func (m *NoticeDetailResponse) String() string { return proto.CompactTextString(m) }
func (*NoticeDetailResponse) ProtoMessage()    {}
func (*NoticeDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0b73ff15a9f3a03e, []int{17}
}
func (m *NoticeDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeDetailResponse.Unmarshal(m, b)
}
func (m *NoticeDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeDetailResponse.Marshal(b, m, deterministic)
}
func (dst *NoticeDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeDetailResponse.Merge(dst, src)
}
func (m *NoticeDetailResponse) XXX_Size() int {
	return xxx_messageInfo_NoticeDetailResponse.Size(m)
}
func (m *NoticeDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeDetailResponse proto.InternalMessageInfo

func (m *NoticeDetailResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *NoticeDetailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NoticeDetailResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NoticeDetailResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NoticeDetailResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NoticeDetailResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *NoticeDetailResponse) GetCovers() []byte {
	if m != nil {
		return m.Covers
	}
	return nil
}

func (m *NoticeDetailResponse) GetContentImages() []byte {
	if m != nil {
		return m.ContentImages
	}
	return nil
}

func (m *NoticeDetailResponse) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NoticeDetailResponse) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *NoticeDetailResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *NoticeDetailResponse) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *NoticeDetailResponse) GetShares() int32 {
	if m != nil {
		return m.Shares
	}
	return 0
}

func (m *NoticeDetailResponse) GetHits() int32 {
	if m != nil {
		return m.Hits
	}
	return 0
}

func (m *NoticeDetailResponse) GetComments() int32 {
	if m != nil {
		return m.Comments
	}
	return 0
}

func (m *NoticeDetailResponse) GetDisplayMark() bool {
	if m != nil {
		return m.DisplayMark
	}
	return false
}

func (m *NoticeDetailResponse) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *NoticeDetailResponse) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *NoticeDetailResponse) GetAdminId() int32 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *NoticeDetailResponse) GetAdminNickname() string {
	if m != nil {
		return m.AdminNickname
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonErrResponse)(nil), "g2u.CommonErrResponse")
	proto.RegisterType((*HelloRequest)(nil), "g2u.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "g2u.HelloResponse")
	proto.RegisterType((*RegisterPhoneRequest)(nil), "g2u.RegisterPhoneRequest")
	proto.RegisterType((*RegisterEmailRequest)(nil), "g2u.RegisterEmailRequest")
	proto.RegisterType((*LoginRequest)(nil), "g2u.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "g2u.LoginResponse")
	proto.RegisterType((*ForgetRequest)(nil), "g2u.ForgetRequest")
	proto.RegisterType((*ForgetResponse)(nil), "g2u.ForgetResponse")
	proto.RegisterType((*SecurityRequest)(nil), "g2u.SecurityRequest")
	proto.RegisterType((*SecurityResponse)(nil), "g2u.SecurityResponse")
	proto.RegisterType((*SmsRequest)(nil), "g2u.SmsRequest")
	proto.RegisterType((*EmailRequest)(nil), "g2u.EmailRequest")
	proto.RegisterType((*ChangePwdRequest)(nil), "g2u.ChangePwdRequest")
	proto.RegisterType((*NoticeListRequest)(nil), "g2u.NoticeListRequest")
	proto.RegisterType((*NoticeListResponse)(nil), "g2u.NoticeListResponse")
	proto.RegisterType((*NoticeListResponse_Notice)(nil), "g2u.NoticeListResponse.Notice")
	proto.RegisterType((*NoticeDetailRequest)(nil), "g2u.NoticeDetailRequest")
	proto.RegisterType((*NoticeDetailResponse)(nil), "g2u.NoticeDetailResponse")
}

func init() { proto.RegisterFile("rpc/user.proto", fileDescriptor_user_0b73ff15a9f3a03e) }

var fileDescriptor_user_0b73ff15a9f3a03e = []byte{
	// 986 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xed, 0x6e, 0xe3, 0x44,
	0x17, 0x6e, 0xbe, 0x9b, 0x93, 0xaf, 0x76, 0x9a, 0xb7, 0xaf, 0x37, 0x48, 0x4b, 0xb0, 0x68, 0x55,
	0x09, 0xa9, 0xac, 0x0a, 0xaa, 0x90, 0x00, 0xad, 0xa0, 0xed, 0x8a, 0xd5, 0x2e, 0x55, 0xe5, 0x2c,
	0xbf, 0x23, 0x63, 0x1f, 0x39, 0xa3, 0xc6, 0x76, 0x98, 0x99, 0x6c, 0xc8, 0x45, 0x70, 0x23, 0xfc,
	0xe3, 0xd6, 0xb8, 0x02, 0x34, 0x73, 0xc6, 0xae, 0xe3, 0x94, 0xc0, 0x56, 0xe2, 0x57, 0xe6, 0x3c,
	0x73, 0xe6, 0x7c, 0xfb, 0x3c, 0x81, 0xbe, 0x58, 0x04, 0x9f, 0x2f, 0x25, 0x8a, 0xf3, 0x85, 0x48,
	0x55, 0xca, 0x6a, 0xd1, 0xc5, 0xd2, 0x7d, 0x09, 0x87, 0x57, 0x69, 0x1c, 0xa7, 0xc9, 0x8d, 0x10,
	0x1e, 0xca, 0x45, 0x9a, 0x48, 0x64, 0x07, 0x50, 0x43, 0x21, 0x9c, 0xca, 0xb8, 0x72, 0xd6, 0xf0,
	0xf4, 0x91, 0x39, 0xd0, 0x8a, 0x51, 0x4a, 0x3f, 0x42, 0xa7, 0x3a, 0xae, 0x9c, 0xb5, 0xbd, 0x4c,
	0x74, 0x5d, 0xe8, 0xfe, 0x80, 0xf3, 0x79, 0xea, 0xe1, 0x2f, 0x4b, 0x94, 0x8a, 0x31, 0xa8, 0x27,
	0x7e, 0x8c, 0xe6, 0x71, 0xdb, 0x33, 0x67, 0xf7, 0x33, 0xe8, 0x59, 0x1d, 0xeb, 0x60, 0x04, 0xfb,
	0x91, 0x40, 0x54, 0x3c, 0x89, 0xac, 0xbd, 0x5c, 0x76, 0x7f, 0xab, 0xc0, 0xd0, 0xc3, 0x88, 0x4b,
	0x85, 0xe2, 0x6e, 0x96, 0x26, 0x98, 0x59, 0x1e, 0x42, 0x63, 0xa1, 0x65, 0x6b, 0x9a, 0x04, 0x1d,
	0xeb, 0x62, 0x15, 0x5a, 0x2b, 0xfa, 0xc8, 0x3e, 0x86, 0x0e, 0x4f, 0xde, 0x73, 0x85, 0xd3, 0x20,
	0x0d, 0xd1, 0xa9, 0x9b, 0x1b, 0x20, 0xe8, 0x2a, 0x0d, 0x51, 0x27, 0x13, 0xa4, 0xcb, 0x44, 0x89,
	0xb5, 0xd3, 0x30, 0x29, 0x66, 0xa2, 0x0e, 0xde, 0xbc, 0x69, 0x52, 0xf0, 0xfa, 0xbc, 0x11, 0xcf,
	0x4d, 0xec, 0xf3, 0x79, 0x21, 0x1e, 0xd4, 0x72, 0x16, 0x8f, 0x11, 0xfe, 0xfb, 0x78, 0x2e, 0xa1,
	0xfb, 0x36, 0x8d, 0x78, 0xf2, 0x81, 0x65, 0x71, 0xbf, 0x86, 0x9e, 0x7d, 0xf7, 0x84, 0x2e, 0x9f,
	0x40, 0xef, 0x55, 0x2a, 0x22, 0x54, 0x3b, 0xbd, 0xba, 0x33, 0xe8, 0x67, 0x6a, 0x1f, 0xee, 0xe4,
	0xc1, 0x66, 0xad, 0x98, 0x49, 0x5e, 0xe6, 0x7a, 0xa1, 0xcc, 0xee, 0x0a, 0x06, 0x13, 0x0c, 0x96,
	0x82, 0xab, 0xf5, 0xee, 0x42, 0x9c, 0xc2, 0xc0, 0x1c, 0xa6, 0xfe, 0x52, 0xcd, 0xa8, 0x03, 0xe4,
	0xb6, 0x67, 0xe0, 0xef, 0x96, 0x6a, 0x66, 0x9a, 0x70, 0x0a, 0x03, 0x63, 0xb9, 0xa0, 0x47, 0x61,
	0xf4, 0x0c, 0x9c, 0xe9, 0xb9, 0x3e, 0x1c, 0x3c, 0x38, 0x7e, 0x42, 0x92, 0x9f, 0x40, 0x57, 0xda,
	0xf7, 0xd3, 0x7b, 0x5c, 0x1b, 0x27, 0x5d, 0xaf, 0x93, 0x61, 0x6f, 0x70, 0xed, 0x5e, 0x02, 0x4c,
	0x62, 0xb9, 0x3b, 0x2d, 0x06, 0x75, 0xb5, 0x5e, 0x90, 0xf5, 0x86, 0x67, 0xce, 0xee, 0xa7, 0xd0,
	0xfd, 0xe7, 0x01, 0x75, 0xdf, 0xc0, 0xc1, 0xd5, 0xcc, 0x4f, 0x22, 0xbc, 0x5b, 0x85, 0x99, 0x66,
	0x39, 0xa8, 0xca, 0x56, 0x50, 0x0f, 0x61, 0x54, 0x8b, 0x0d, 0x8f, 0xe0, 0xf0, 0x36, 0x55, 0x3c,
	0xc0, 0xb7, 0x5c, 0xe6, 0xb3, 0xf1, 0x1c, 0x80, 0xc0, 0x77, 0x3a, 0x42, 0xaa, 0x4a, 0x01, 0xd1,
	0x5f, 0xff, 0x44, 0xf9, 0x42, 0x79, 0xe9, 0xca, 0xc6, 0x9f, 0xcb, 0xec, 0x18, 0x9a, 0x37, 0x49,
	0xa8, 0x6f, 0x6a, 0xe6, 0xc6, 0x4a, 0xee, 0x9f, 0x15, 0x60, 0x45, 0x4f, 0xb6, 0xf2, 0x97, 0xd0,
	0x4c, 0x0c, 0xea, 0x54, 0xc6, 0xb5, 0xb3, 0xce, 0xc5, 0xf3, 0xf3, 0xe8, 0x62, 0x79, 0xbe, 0xad,
	0x68, 0x21, 0xcf, 0x6a, 0x67, 0x1d, 0xab, 0x3e, 0xda, 0xb1, 0xda, 0x46, 0xc7, 0x46, 0xbf, 0x42,
	0x93, 0x5e, 0xb3, 0x3e, 0x54, 0x79, 0x68, 0x13, 0xaa, 0xf2, 0x50, 0xd7, 0x44, 0x71, 0x35, 0xcf,
	0x6b, 0x62, 0x04, 0x36, 0x86, 0xce, 0x35, 0xca, 0x40, 0xf0, 0x85, 0xe2, 0x69, 0x62, 0xad, 0x15,
	0x21, 0x76, 0x0a, 0xfd, 0x40, 0xa0, 0xaf, 0xf0, 0xda, 0x57, 0xf8, 0x8e, 0xc7, 0xd9, 0x52, 0x28,
	0xa1, 0xee, 0x09, 0x1c, 0x91, 0xe7, 0x6b, 0x54, 0x85, 0xbe, 0x96, 0xc2, 0x70, 0xff, 0xa8, 0xc3,
	0x70, 0x53, 0xef, 0x09, 0x73, 0x49, 0x46, 0x6b, 0xdb, 0xb9, 0xd5, 0x4b, 0xb9, 0x85, 0x85, 0xdc,
	0x1a, 0x94, 0x5b, 0x01, 0xa2, 0x65, 0x96, 0x28, 0x4c, 0x94, 0xdd, 0x5a, 0x99, 0xa8, 0x5b, 0x1b,
	0xa4, 0xef, 0x51, 0x48, 0xa7, 0x65, 0xc6, 0xcb, 0x4a, 0xec, 0x04, 0xfa, 0x56, 0x65, 0xca, 0x63,
	0x3f, 0x42, 0xe9, 0xec, 0x9b, 0xfb, 0x9e, 0x45, 0x5f, 0x1b, 0x30, 0x9f, 0xf8, 0xf6, 0xc3, 0xc4,
	0xb3, 0x8f, 0xa0, 0xad, 0x7f, 0xa7, 0x86, 0x71, 0x80, 0x88, 0x44, 0x03, 0xb7, 0x7e, 0x8c, 0xda,
	0x9f, 0xfe, 0x96, 0x53, 0xe1, 0x74, 0xcc, 0x8d, 0x95, 0x34, 0xbe, 0x42, 0x1e, 0xcd, 0x94, 0xd3,
	0xa5, 0x11, 0x23, 0x49, 0xe3, 0x72, 0xe6, 0x0b, 0x94, 0x4e, 0x8f, 0x70, 0x92, 0xb4, 0xe3, 0x19,
	0x57, 0xd2, 0xe9, 0x93, 0x63, 0x7d, 0xd6, 0x23, 0x1c, 0xa4, 0x71, 0x8c, 0x89, 0x92, 0xce, 0x80,
	0x46, 0x38, 0x93, 0x4d, 0xff, 0xb9, 0x5c, 0xcc, 0xfd, 0xf5, 0x8f, 0xbe, 0xb8, 0x77, 0x0e, 0xc6,
	0x95, 0xb3, 0x7d, 0xaf, 0x08, 0x69, 0x46, 0xa0, 0x4e, 0x4f, 0x95, 0x6e, 0xfe, 0x21, 0x31, 0x02,
	0x41, 0xba, 0xf1, 0x5a, 0x61, 0xb9, 0x08, 0x73, 0x05, 0x46, 0x0a, 0x04, 0x19, 0x05, 0x07, 0x5a,
	0x7e, 0x18, 0xf3, 0xe4, 0x75, 0xe8, 0x1c, 0x11, 0x65, 0x58, 0x51, 0x57, 0xd3, 0x1c, 0xa7, 0x09,
	0x0f, 0xee, 0x4d, 0x5d, 0x86, 0xb4, 0xc6, 0x0c, 0x7a, 0x6b, 0xc1, 0x8b, 0xdf, 0x1b, 0xd0, 0xfa,
	0x49, 0xa2, 0xf0, 0xee, 0xae, 0xd8, 0x0b, 0x68, 0x18, 0x7a, 0x66, 0x87, 0xe6, 0xeb, 0x29, 0xd2,
	0xf9, 0x88, 0x15, 0x21, 0x1a, 0x2b, 0x77, 0x8f, 0xbd, 0x82, 0x41, 0x46, 0x89, 0xdf, 0xaf, 0x0d,
	0x49, 0xb3, 0x67, 0x46, 0xf1, 0x31, 0xe2, 0x1e, 0x1d, 0x9b, 0xab, 0xad, 0xbf, 0x19, 0x65, 0x3b,
	0x66, 0x77, 0x95, 0xec, 0x14, 0xf7, 0xd9, 0x0e, 0x3b, 0x2f, 0xa0, 0x61, 0xb8, 0xcd, 0x66, 0x50,
	0xe4, 0x47, 0x9b, 0xc1, 0x06, 0xf5, 0xb9, 0x7b, 0xec, 0x12, 0xda, 0xc4, 0x54, 0x77, 0xab, 0x90,
	0x91, 0xca, 0x06, 0xc1, 0x8d, 0x8e, 0x36, 0xb0, 0xfc, 0xdd, 0xb7, 0xd0, 0xd5, 0x54, 0x90, 0x51,
	0x00, 0x1b, 0x1a, 0xb5, 0x12, 0x15, 0x8d, 0xfe, 0x57, 0x42, 0xf3, 0xe7, 0xdf, 0x40, 0x3b, 0x5f,
	0xbe, 0x8c, 0xb4, 0xca, 0xcb, 0x78, 0x47, 0x9a, 0x5f, 0x42, 0x6b, 0x82, 0x49, 0x38, 0x89, 0x25,
	0x1b, 0x90, 0x87, 0x9c, 0x26, 0x76, 0xbc, 0xfa, 0x0a, 0xda, 0xfa, 0x15, 0x95, 0x97, 0x0a, 0xf4,
	0x2f, 0xcb, 0xfa, 0x32, 0x5b, 0xe4, 0x7a, 0x95, 0xb2, 0xe3, 0xad, 0xdd, 0x4a, 0xef, 0xff, 0xff,
	0x37, 0x3b, 0xd7, 0xdd, 0x63, 0x37, 0xd0, 0x2d, 0x2e, 0x26, 0xe6, 0x14, 0x54, 0x37, 0x76, 0xda,
	0xe8, 0xd9, 0x23, 0x37, 0x99, 0x99, 0x9f, 0x9b, 0xe6, 0x0f, 0xeb, 0x17, 0x7f, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x6d, 0x24, 0x87, 0x82, 0xc2, 0x0a, 0x00, 0x00,
}
