// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/waller.proto

package g2u

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest2 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest2) Reset()         { *m = HelloRequest2{} }
func (m *HelloRequest2) String() string { return proto.CompactTextString(m) }
func (*HelloRequest2) ProtoMessage()    {}
func (*HelloRequest2) Descriptor() ([]byte, []int) {
	return fileDescriptor_waller_bd826d666384daa7, []int{0}
}
func (m *HelloRequest2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest2.Unmarshal(m, b)
}
func (m *HelloRequest2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest2.Marshal(b, m, deterministic)
}
func (dst *HelloRequest2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest2.Merge(dst, src)
}
func (m *HelloRequest2) XXX_Size() int {
	return xxx_messageInfo_HelloRequest2.Size(m)
}
func (m *HelloRequest2) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest2.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest2 proto.InternalMessageInfo

func (m *HelloRequest2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse2 struct {
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse2) Reset()         { *m = HelloResponse2{} }
func (m *HelloResponse2) String() string { return proto.CompactTextString(m) }
func (*HelloResponse2) ProtoMessage()    {}
func (*HelloResponse2) Descriptor() ([]byte, []int) {
	return fileDescriptor_waller_bd826d666384daa7, []int{1}
}
func (m *HelloResponse2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse2.Unmarshal(m, b)
}
func (m *HelloResponse2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse2.Marshal(b, m, deterministic)
}
func (dst *HelloResponse2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse2.Merge(dst, src)
}
func (m *HelloResponse2) XXX_Size() int {
	return xxx_messageInfo_HelloResponse2.Size(m)
}
func (m *HelloResponse2) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse2.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse2 proto.InternalMessageInfo

func (m *HelloResponse2) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type CreateWalletRequest struct {
	Userid               int32    `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Tokenid              int32    `protobuf:"varint,2,opt,name=tokenid" json:"tokenid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWalletRequest) Reset()         { *m = CreateWalletRequest{} }
func (m *CreateWalletRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWalletRequest) ProtoMessage()    {}
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_waller_bd826d666384daa7, []int{2}
}
func (m *CreateWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWalletRequest.Unmarshal(m, b)
}
func (m *CreateWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWalletRequest.Marshal(b, m, deterministic)
}
func (dst *CreateWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWalletRequest.Merge(dst, src)
}
func (m *CreateWalletRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWalletRequest.Size(m)
}
func (m *CreateWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWalletRequest proto.InternalMessageInfo

func (m *CreateWalletRequest) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *CreateWalletRequest) GetTokenid() int32 {
	if m != nil {
		return m.Tokenid
	}
	return 0
}

type CreateWalletResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWalletResponse) Reset()         { *m = CreateWalletResponse{} }
func (m *CreateWalletResponse) String() string { return proto.CompactTextString(m) }
func (*CreateWalletResponse) ProtoMessage()    {}
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_waller_bd826d666384daa7, []int{3}
}
func (m *CreateWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWalletResponse.Unmarshal(m, b)
}
func (m *CreateWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWalletResponse.Marshal(b, m, deterministic)
}
func (dst *CreateWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWalletResponse.Merge(dst, src)
}
func (m *CreateWalletResponse) XXX_Size() int {
	return xxx_messageInfo_CreateWalletResponse.Size(m)
}
func (m *CreateWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWalletResponse proto.InternalMessageInfo

func (m *CreateWalletResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateWalletResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreateWalletResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateWalletResponse) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest2)(nil), "g2u.HelloRequest2")
	proto.RegisterType((*HelloResponse2)(nil), "g2u.HelloResponse2")
	proto.RegisterType((*CreateWalletRequest)(nil), "g2u.CreateWalletRequest")
	proto.RegisterType((*CreateWalletResponse)(nil), "g2u.CreateWalletResponse")
}

func init() { proto.RegisterFile("rpc/waller.proto", fileDescriptor_waller_bd826d666384daa7) }

var fileDescriptor_waller_bd826d666384daa7 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x6c, 0x4c, 0x53, 0xf5, 0xa1, 0xa5, 0xbc, 0x8a, 0xac, 0x39, 0xc9, 0x7a, 0xf1, 0x20, 0x11,
	0xd6, 0x4f, 0x10, 0xa9, 0xe7, 0x5c, 0x3c, 0xaf, 0xdd, 0x47, 0x08, 0xa6, 0xd9, 0xb8, 0xbb, 0xa1,
	0xf4, 0x1b, 0xfc, 0x69, 0xd9, 0x97, 0xb4, 0xb4, 0xd0, 0xdb, 0xbc, 0xc9, 0x30, 0x33, 0x99, 0x85,
	0x85, 0xeb, 0xd6, 0xaf, 0x5b, 0xdd, 0x34, 0xe4, 0x8a, 0xce, 0xd9, 0x60, 0x31, 0xad, 0x54, 0x2f,
	0x9f, 0xe0, 0xf6, 0x93, 0x9a, 0xc6, 0x96, 0xf4, 0xdb, 0x93, 0x0f, 0x0a, 0x11, 0xa6, 0xad, 0xde,
	0x90, 0x48, 0x1e, 0x93, 0xe7, 0xeb, 0x92, 0xb1, 0x7c, 0x81, 0xf9, 0x28, 0xf2, 0x9d, 0x6d, 0x3d,
	0x29, 0xcc, 0xe1, 0xaa, 0x72, 0x44, 0xa1, 0x6e, 0x2b, 0x71, 0xc1, 0xca, 0xc3, 0x2d, 0x57, 0xb0,
	0x7c, 0x77, 0xa4, 0x03, 0x7d, 0xc5, 0xb4, 0x30, 0x3a, 0xe3, 0x3d, 0xcc, 0x7a, 0x4f, 0xae, 0x36,
	0x6c, 0x9d, 0x95, 0xe3, 0x85, 0x02, 0x2e, 0x83, 0xfd, 0xa1, 0xb6, 0x36, 0xec, 0x94, 0x95, 0xfb,
	0x53, 0x1a, 0xb8, 0x3b, 0x35, 0x1a, 0xd2, 0x63, 0xc5, 0xb5, 0x35, 0x87, 0x8a, 0x11, 0xe3, 0x02,
	0xd2, 0x8d, 0xdf, 0x77, 0x89, 0x30, 0xaa, 0xc2, 0xae, 0x23, 0x91, 0x0e, 0xaa, 0x88, 0x23, 0xa7,
	0x8d, 0x71, 0x62, 0x3a, 0x70, 0x11, 0xab, 0xbf, 0x04, 0xe6, 0x2b, 0x1d, 0x68, 0xab, 0x77, 0x8a,
	0x83, 0x1c, 0x2a, 0xc8, 0xf8, 0x7f, 0x11, 0x8b, 0x4a, 0xf5, 0xc5, 0xc9, 0x40, 0xf9, 0xf2, 0x98,
	0x1b, 0xf7, 0x90, 0x13, 0xfc, 0x80, 0x9b, 0xe3, 0xb2, 0x28, 0x58, 0x76, 0x66, 0x88, 0xfc, 0xe1,
	0xcc, 0x97, 0xc1, 0x47, 0x4e, 0xbe, 0x67, 0xfc, 0x36, 0x6f, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x0f, 0x38, 0x56, 0x54, 0xaf, 0x01, 0x00, 0x00,
}
