// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/waller.proto

package g2u

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest2 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest2) Reset()         { *m = HelloRequest2{} }
func (m *HelloRequest2) String() string { return proto.CompactTextString(m) }
func (*HelloRequest2) ProtoMessage()    {}
func (*HelloRequest2) Descriptor() ([]byte, []int) {
	return fileDescriptor_waller_b84d8f12a46581e0, []int{0}
}
func (m *HelloRequest2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest2.Unmarshal(m, b)
}
func (m *HelloRequest2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest2.Marshal(b, m, deterministic)
}
func (dst *HelloRequest2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest2.Merge(dst, src)
}
func (m *HelloRequest2) XXX_Size() int {
	return xxx_messageInfo_HelloRequest2.Size(m)
}
func (m *HelloRequest2) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest2.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest2 proto.InternalMessageInfo

func (m *HelloRequest2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse2 struct {
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse2) Reset()         { *m = HelloResponse2{} }
func (m *HelloResponse2) String() string { return proto.CompactTextString(m) }
func (*HelloResponse2) ProtoMessage()    {}
func (*HelloResponse2) Descriptor() ([]byte, []int) {
	return fileDescriptor_waller_b84d8f12a46581e0, []int{1}
}
func (m *HelloResponse2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse2.Unmarshal(m, b)
}
func (m *HelloResponse2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse2.Marshal(b, m, deterministic)
}
func (dst *HelloResponse2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse2.Merge(dst, src)
}
func (m *HelloResponse2) XXX_Size() int {
	return xxx_messageInfo_HelloResponse2.Size(m)
}
func (m *HelloResponse2) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse2.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse2 proto.InternalMessageInfo

func (m *HelloResponse2) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest2)(nil), "g2u.HelloRequest2")
	proto.RegisterType((*HelloResponse2)(nil), "g2u.HelloResponse2")
}

func init() { proto.RegisterFile("rpc/waller.proto", fileDescriptor_waller_b84d8f12a46581e0) }

var fileDescriptor_waller_b84d8f12a46581e0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2a, 0x48, 0xd6,
	0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x37,
	0x2a, 0x55, 0x52, 0xe6, 0xe2, 0xf5, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x31, 0x12, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0xb3, 0x95, 0x74, 0xb8, 0xf8, 0xa0, 0x8a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x8d,
	0x84, 0xa4, 0xb8, 0x38, 0xd2, 0x8b, 0x52, 0x53, 0x4b, 0x32, 0xf3, 0xd2, 0x25, 0x98, 0xc0, 0x2a,
	0xe1, 0x7c, 0x23, 0x17, 0x2e, 0x3e, 0xf7, 0xc4, 0x92, 0xd4, 0xf2, 0xc4, 0x4a, 0xa3, 0x70, 0xb0,
	0x7d, 0x42, 0x46, 0x5c, 0xac, 0x60, 0xfd, 0x42, 0x42, 0x7a, 0xe9, 0x46, 0xa5, 0x7a, 0x28, 0x16,
	0x4a, 0x09, 0x23, 0x8b, 0x41, 0xcd, 0x57, 0x62, 0x48, 0x62, 0x03, 0x3b, 0xd2, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0x41, 0x20, 0x55, 0xb8, 0x00, 0x00, 0x00,
}
